version: "3.8"
services:

  postgres-db:
    image: postgres:12
    restart: always
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_root
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=localisation_db

  # http://localhost:8080
  # Information de connection à postgres-db
  # Server: postgres-db:5432
  # Username: ${POSTGRES_USER}
  # Password: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  # http://localhost:8081
  # Username: guest
  # Password: guest
  rabbtimq-management:
    image: rabbitmq:3-management
    volumes:
      - 'mq_data:/var/lib/rabbitmq'
    ports:
      - 8081:15672
      - 5672:5672

  # http://localhost:7979/hystrix-dashboard
  hystrix:
    image: kennedyoliveira/hystrix-dashboard:1.5.6
    ports: 
      - '7979:7979'

volumes: 
  pg_data:
  mq_data:
